# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
# Licence statement: MPL-2.0 for code, CC-BY-SA-4.0 for documentation
# Funding platforms for hyperpolymath projects
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

buy_me_a_coffee: jonathan.jewell
community_bridge: jonathan-jewell
github: hyperpolymath
issuehunt: hyperpolymath
ko_fi: hyperpolymath
lfx_crowdfunding: hyperpolymath
liberapay: hyperpolymath
open_collective: jonathan-jewell
patreon: cc_studio
polar: hyperpolymath
thanks_dev: hyperpolymath
