# SPDX-License-Identifier: PMPL-1.0-or-later

defmodule FeedbackATron.ReportGenerator do
  @moduledoc """
  Report generator for migration observation data.

  Three report types:
  1. **Per-repo mini report** — before/after table, issues, time taken
  2. **Cross-repo aggregation** — common pain points, average health improvement
  3. **v13 pre-release trial report** — structured for ReScript team
  """

  require Logger

  @doc """
  Generate a per-repo migration report from a completed session.
  """
  def per_repo_report(session) do
    before = session.before_snapshot["migration_metrics"] || %{}
    after_m = session.after_snapshot["migration_metrics"] || %{}

    duration =
      if session.ended_at,
        do: DateTime.diff(session.ended_at, session.started_at, :second),
        else: 0

    issues =
      session.events
      |> Enum.filter(fn e -> e.type == :issue end)
      |> Enum.map(fn e -> "- #{e.description} (#{e.severity})" end)
      |> Enum.join("\n")

    complications =
      session.events
      |> Enum.filter(fn e -> e.type == :complication end)
      |> Enum.map(fn e -> "- #{e.description}" end)
      |> Enum.join("\n")

    """
    # Migration Report: #{session.label}

    **Repo:** #{extract_repo_name(session.repo_path)}
    **Duration:** #{format_duration(duration)}
    **Session ID:** #{session.session_id}

    ## Before / After Comparison

    | Metric | Before | After | Delta |
    |--------|--------|-------|-------|
    | Health Score | #{before["health_score"] || "-"} | #{after_m["health_score"] || "-"} | #{delta(before["health_score"], after_m["health_score"])} |
    | Deprecated APIs | #{before["deprecated_api_count"] || "-"} | #{after_m["deprecated_api_count"] || "-"} | #{delta(before["deprecated_api_count"], after_m["deprecated_api_count"])} |
    | Modern APIs | #{before["modern_api_count"] || "-"} | #{after_m["modern_api_count"] || "-"} | #{delta(before["modern_api_count"], after_m["modern_api_count"])} |
    | Version | #{before["version_bracket"] || "-"} | #{after_m["version_bracket"] || "-"} | - |
    | Config | #{before["config_format"] || "-"} | #{after_m["config_format"] || "-"} | - |
    | Files | #{before["file_count"] || "-"} | #{after_m["file_count"] || "-"} | #{delta(before["file_count"], after_m["file_count"])} |
    | Lines | #{before["rescript_lines"] || "-"} | #{after_m["rescript_lines"] || "-"} | #{delta(before["rescript_lines"], after_m["rescript_lines"])} |

    #{if issues != "", do: "## Issues Discovered\n\n#{issues}\n", else: ""}
    #{if complications != "", do: "## Complications\n\n#{complications}\n", else: ""}
    #{if session.notes, do: "## Notes\n\n#{session.notes}\n", else: ""}

    ## Recommendations

    #{generate_recommendations(before, after_m)}

    ---
    _Generated by feedback-o-tron report generator_
    """
  end

  @doc """
  Generate a cross-repo aggregation report from multiple sessions.
  """
  def cross_repo_report(sessions) when is_list(sessions) do
    count = length(sessions)

    health_deltas =
      sessions
      |> Enum.map(fn s ->
        before_h = get_in(s.before_snapshot, ["migration_metrics", "health_score"]) || 0.0
        after_h = get_in(s.after_snapshot, ["migration_metrics", "health_score"]) || 0.0
        after_h - before_h
      end)

    avg_health_delta =
      if count > 0, do: Enum.sum(health_deltas) / count, else: 0.0

    total_deprecated_removed =
      sessions
      |> Enum.map(fn s ->
        before_d =
          get_in(s.before_snapshot, ["migration_metrics", "deprecated_api_count"]) || 0

        after_d =
          get_in(s.after_snapshot, ["migration_metrics", "deprecated_api_count"]) || 0

        before_d - after_d
      end)
      |> Enum.sum()

    all_issues =
      sessions
      |> Enum.flat_map(fn s ->
        s.events
        |> Enum.filter(fn e -> e.type == :issue end)
        |> Enum.map(fn e -> e.description end)
      end)

    # Group issues by frequency
    issue_frequency =
      all_issues
      |> Enum.frequencies()
      |> Enum.sort_by(fn {_desc, count} -> count end, :desc)
      |> Enum.take(20)

    issue_table =
      issue_frequency
      |> Enum.map(fn {desc, count} -> "| #{desc} | #{count} |" end)
      |> Enum.join("\n")

    durations =
      sessions
      |> Enum.map(fn s ->
        if s.ended_at, do: DateTime.diff(s.ended_at, s.started_at, :second), else: 0
      end)

    avg_duration = if count > 0, do: div(Enum.sum(durations), count), else: 0

    """
    # Cross-Repo Migration Report

    **Sessions:** #{count}
    **Average health improvement:** #{Float.round(avg_health_delta, 3)}
    **Total deprecated APIs removed:** #{total_deprecated_removed}
    **Average session duration:** #{format_duration(avg_duration)}

    ## Migration Velocity

    | Repo | Health Delta | Deprecated Removed | Duration |
    |------|-------------|-------------------|----------|
    #{sessions |> Enum.map(&format_session_row/1) |> Enum.join("\n")}

    ## Common Pain Points

    | Issue | Frequency |
    |-------|-----------|
    #{issue_table}

    ---
    _Generated by feedback-o-tron report generator_
    """
  end

  @doc """
  Generate a v13 pre-release trial report structured for the ReScript team.
  """
  def v13_trial_report(sessions) when is_list(sessions) do
    v13_sessions =
      sessions
      |> Enum.filter(fn s ->
        version = get_in(s.after_snapshot, ["migration_metrics", "version_bracket"])
        version && String.contains?(to_string(version), "V13")
      end)

    non_v13 = sessions -- v13_sessions

    regressions =
      sessions
      |> Enum.flat_map(fn s ->
        s.events
        |> Enum.filter(fn e -> e.type == :issue && e.severity == :critical end)
        |> Enum.map(fn e ->
          %{repo: extract_repo_name(s.repo_path), description: e.description}
        end)
      end)

    """
    # ReScript v13 Pre-Release Trial Report

    **Date:** #{DateTime.utc_now() |> DateTime.to_iso8601()}
    **Total repos tested:** #{length(sessions)}
    **Repos on v13:** #{length(v13_sessions)}
    **Repos on earlier versions:** #{length(non_v13)}

    ## Performance Data

    #{format_performance_table(sessions)}

    ## Regressions

    #{if length(regressions) > 0 do
      regressions
      |> Enum.map(fn r -> "- **#{r.repo}**: #{r.description}" end)
      |> Enum.join("\n")
    else
      "No regressions detected."
    end}

    ## Missing Features / v14 Opportunities

    #{format_missing_features(sessions)}

    ## Individual Program Stats

    #{sessions |> Enum.map(&format_program_stats/1) |> Enum.join("\n\n")}

    ---
    _Generated by feedback-o-tron for the ReScript team_
    """
  end

  # --- Private Helpers ---

  defp delta(nil, _), do: "-"
  defp delta(_, nil), do: "-"

  defp delta(before, after_val) when is_number(before) and is_number(after_val) do
    d = after_val - before

    cond do
      d > 0 -> "+#{d}"
      d < 0 -> "#{d}"
      true -> "0"
    end
  end

  defp delta(_, _), do: "-"

  defp format_duration(seconds) when seconds < 60, do: "#{seconds}s"
  defp format_duration(seconds) when seconds < 3600, do: "#{div(seconds, 60)}m #{rem(seconds, 60)}s"

  defp format_duration(seconds),
    do: "#{div(seconds, 3600)}h #{div(rem(seconds, 3600), 60)}m"

  defp format_session_row(session) do
    repo = extract_repo_name(session.repo_path)
    before_h = get_in(session.before_snapshot, ["migration_metrics", "health_score"]) || 0.0
    after_h = get_in(session.after_snapshot, ["migration_metrics", "health_score"]) || 0.0
    before_d = get_in(session.before_snapshot, ["migration_metrics", "deprecated_api_count"]) || 0
    after_d = get_in(session.after_snapshot, ["migration_metrics", "deprecated_api_count"]) || 0
    duration = if session.ended_at, do: DateTime.diff(session.ended_at, session.started_at, :second), else: 0

    "| #{repo} | #{Float.round(after_h - before_h, 3)} | #{before_d - after_d} | #{format_duration(duration)} |"
  end

  defp format_performance_table(sessions) do
    rows =
      sessions
      |> Enum.map(fn s ->
        repo = extract_repo_name(s.repo_path)
        before_bt = get_in(s.before_snapshot, ["migration_metrics", "build_time_ms"])
        after_bt = get_in(s.after_snapshot, ["migration_metrics", "build_time_ms"])
        before_bs = get_in(s.before_snapshot, ["migration_metrics", "bundle_size_bytes"])
        after_bs = get_in(s.after_snapshot, ["migration_metrics", "bundle_size_bytes"])

        "| #{repo} | #{before_bt || "-"} | #{after_bt || "-"} | #{before_bs || "-"} | #{after_bs || "-"} |"
      end)
      |> Enum.join("\n")

    """
    | Repo | Build Time (before) | Build Time (after) | Bundle Size (before) | Bundle Size (after) |
    |------|--------------------|--------------------|---------------------|---------------------|
    #{rows}
    """
  end

  defp format_missing_features(sessions) do
    features =
      sessions
      |> Enum.flat_map(fn s ->
        s.events
        |> Enum.filter(fn e -> e.type == :note end)
        |> Enum.filter(fn e ->
          desc = String.downcase(e.description)
          String.contains?(desc, "missing") || String.contains?(desc, "feature")
        end)
        |> Enum.map(fn e -> e.description end)
      end)
      |> Enum.uniq()

    if length(features) > 0 do
      features
      |> Enum.map(fn f -> "- #{f}" end)
      |> Enum.join("\n")
    else
      "No missing features reported."
    end
  end

  defp format_program_stats(session) do
    repo = extract_repo_name(session.repo_path)
    after_m = session.after_snapshot["migration_metrics"] || %{}

    """
    ### #{repo}

    - **Version:** #{after_m["version_bracket"] || "unknown"}
    - **Files:** #{after_m["file_count"] || "?"}, **Lines:** #{after_m["rescript_lines"] || "?"}
    - **Health:** #{after_m["health_score"] || "?"}, **Ratio:** #{after_m["api_migration_ratio"] || "?"}
    - **Deprecated:** #{after_m["deprecated_api_count"] || 0}, **Modern:** #{after_m["modern_api_count"] || 0}
    """
  end

  defp generate_recommendations(before, after_m) do
    recs = []

    recs =
      if (after_m["deprecated_api_count"] || 0) > 0 do
        recs ++ ["- Migrate remaining #{after_m["deprecated_api_count"]} deprecated API calls to @rescript/core"]
      else
        recs
      end

    recs =
      case after_m["config_format"] do
        f when f in ["BsConfig", "Both"] ->
          recs ++ ["- Migrate bsconfig.json to rescript.json"]
        _ -> recs
      end

    recs =
      case after_m["jsx_version"] do
        3 -> recs ++ ["- Upgrade JSX from v3 to v4"]
        _ -> recs
      end

    recs =
      if after_m["uncurried"] != true do
        recs ++ ["- Enable uncurried mode"]
      else
        recs
      end

    if length(recs) > 0, do: Enum.join(recs, "\n"), else: "All migration targets met."
  end

  defp extract_repo_name(path) do
    path |> String.split("/") |> List.last()
  end
end
